######################################################################
# Automatically generated by qmake (3.0) Tue May 10 12:48:54 2016
######################################################################

TEMPLATE = app
TARGET = JSTest
INCLUDEPATH += .

CONFIG -= qt
CONFIG += c++11

# Input
SOURCES += jstest.cpp
