######################################################################
# Automatically generated by qmake (3.0) Sun May 22 12:56:51 2016
######################################################################

TEMPLATE = app
TARGET = MousePublisher
INCLUDEPATH += .

include($$PWD/../common.pri)

MOC_DIR=$$PWD/build/moc
OBJECTS_DIR=$$PWD/build/objs

# Input
HEADERS += mouse_reader.h publisher.h
SOURCES += main.cpp mouse_reader.cpp publisher.cpp
