######################################################################
# Automatically generated by qmake (3.0) Sun May 22 14:38:12 2016
######################################################################

TEMPLATE = app
TARGET = MousePublisher
INCLUDEPATH += .

include($$PWD/../common.pri)

MOC_DIR=$$PWD/build/moc
OBJECTS_DIR=$$PWD/build/objs

# Input
HEADERS += app.h MouseReader.h QPubApp.h
SOURCES += mouse_main.cpp MouseReader.cpp QPubApp.cpp
