######################################################################
# Automatically generated by qmake (3.0) Sun May 22 12:09:06 2016
######################################################################

TEMPLATE = app
TARGET = MsgBroker
INCLUDEPATH += .

include($$PWD/../common.pri)

# Input
SOURCES += broker_main.cpp
