######################################################################
# Automatically generated by qmake (3.0) Sun May 22 14:03:26 2016
######################################################################

TEMPLATE = app
TARGET = JoystickPublisher
INCLUDEPATH += .

include($$PWD/../common.pri)

MOC_DIR=$$PWD/build/moc
OBJECTS_DIR=$$PWD/build/objs

# Input
HEADERS += app.h JoystickReader.h QPubApp.h
SOURCES += JoystickReader.cpp jp_main.cpp QPubApp.cpp
