######################################################################
# Automatically generated by qmake (3.0) Sun May 22 12:54:30 2016
######################################################################

TEMPLATE = app
TARGET = JoystickPublisher
INCLUDEPATH += .

include($$PWD/../common.pri)

MOC_DIR=$$PWD/build/moc
OBJECTS_DIR=$$PWD/build/objs

# Input
HEADERS += app.h mouse_reader.h publisher.h
SOURCES += jp_main.cpp mouse_reader.cpp publisher.cpp
