######################################################################
# Automatically generated by qmake (3.0) Thu May 12 08:29:15 2016
######################################################################

TEMPLATE = app
TARGET = Subscriber
INCLUDEPATH += .

include($$PWD/../common.pri)

MOC_DIR=$$PWD/build/moc
OBJECTS_DIR=$$PWD/build/objs

# Input
SOURCES += sub_main.cpp
