######################################################################
# Automatically generated by qmake (3.0) Fri May 13 19:07:31 2016
######################################################################

TEMPLATE = app
TARGET = Proxy
INCLUDEPATH += .

include($$PWD/../common.pri)

# Input
SOURCES += main.cpp
