######################################################################
# Automatically generated by qmake (3.0) Tue May 10 12:50:19 2016
######################################################################

TEMPLATE = subdirs

SUBDIRS =	First \
			JSTest\
                        mouse\
                        Extended
