######################################################################
# Automatically generated by qmake (3.0) Sat May 7 23:21:24 2016
######################################################################

TEMPLATE = app
TARGET = First
INCLUDEPATH += .

CONFIG -= qt
CONFIG += c++11

# Input
HEADERS += matrix.h \
    pos.hpp \
    snake.hpp
SOURCES += main.cpp matrix.cpp
