######################################################################
# Automatically generated by qmake (3.0) Thu May 12 09:46:32 2016
######################################################################

TEMPLATE = subdirs

SUBDIRS = Proxy Publisher Subscriber
